### ISSUE TITLE
I'm a newbie, do you have a detailed deployment tutorial for your project?

### ISSUE THREAD

**Issue by szsyzx** [sapphire-sh/slack-twitter-bot#1]
I'm a newbie, do you have a detailed deployment tutorial for your project?

**Comment by sapphire-sh** [comment]
hello, @szsyzx!

1. install node.js on your computer.
  - any recent version of node.js is okay. (an LTS version is recommended)
  - `node -v` should print something like below.
<img width="682" alt="Screen Shot 2022-08-02 at 1 23 00" src="https://user-images.githubusercontent.com/3864286/182197151-b1798d3d-e0d7-4fb4-96eb-24c712c8311e.png">

2. clone this repository.
  - `git clone https://github.com/sapphire-sh/slack-twitter-bot.git`
<img width="682" alt="Screen Shot 2022-08-02 at 1 24 58" src="https://user-images.githubusercontent.com/3864286/182197460-203b117f-f671-49a2-b0ff-0a91476e24db.png">

3. install packages.
  - `cd slack-twitter-bot` to open cloned directory and `npm ci` or `npm install` to install packages.
  - after install, you should have `node_modules` directory.
<img width="682" alt="Screen Shot 2022-08-02 at 1 26 32" src="https://user-images.githubusercontent.com/3864286/182197750-6367a8dc-2e12-48bd-aefd-ee62f1bb754a.png">

4. create twitter tokens file.
  - open your favorite editor and create `data` directory on project root.
  - and create `tokens.json` file inside `data` directory you just created.
  - you should create your own twitter app from https://developer.twitter.com/en/portal/projects-and-apps.
  - you should authenticate your twitter account and get access token with your own twitter app.
    - you may use https://github.com/sapphire-sh/twitter-authentication-server if you prefer.
<img width="1341" alt="Screen Shot 2022-08-02 at 1 17 44" src="https://user-images.githubusercontent.com/3864286/182198023-cc8c6104-f23b-4809-89f0-fb64c5c60837.png">

5. create twitter subscriptions file.
  - open your favorite editor and create `subscriptions.json` file inside `data` directory.
  - if `"type"` is `"user"`, then `"value"` should be the screen name of the user you want to subscribe.
  - if `"type"` is `"list"`, then `"value"` should be the id of the list (you can find it from the url) you want to subscribe.
  - you should create your own slack app and get incoming webhooks (documents below).
    - https://api.slack.com/messaging/webhooks
    - https://slack.com/help/articles/115005265063-Incoming-webhooks-for-Slack
  - you may state `"attribute"` property if you want to:
    - `"strip_retweets"`: if the tweet is a retweet, send retweeted status to the slack channel instead of the original tweet object.
    - `"ignore_retweets"`: skip retweets.
    - `"ignore_non_media_tweets"`: skip tweets with out any media objects.
    - `"ignore_sensitive_tweets"`: skip tweets flagged as sensitive.
<img width="1341" alt="Screen Shot 2022-08-02 at 1 18 19" src="https://user-images.githubusercontent.com/3864286/182198610-b73713e0-81d3-467e-8744-099792c07829.png">

6. start server
  - enter `npm start` on your terminal and press return.
  - the application will start.

**Comment by szsyzx** [comment]
root@vm-standard-a1-flex:~/slack-twitter-bot# bash ./scripts/start.sh
+ docker-compose build
Building server
Sending build context to Docker daemon  309.8kB
Step 1/9 : FROM node:alpine
 ---> 01e8efcc8623
Step 2/9 : RUN mkdir -p /opt/project
 ---> Using cache
 ---> fd57a0d97f5d
Step 3/9 : WORKDIR /opt/project
 ---> Using cache
 ---> 7273cd7123a7
Step 4/9 : RUN node --version
 ---> Using cache
 ---> b53669862f9f
Step 5/9 : RUN npm --version
 ---> Using cache
 ---> 58a36ef04b7b
Step 6/9 : COPY package* ./
 ---> Using cache
 ---> 622d6b9e3abc
Step 7/9 : RUN npm ci
 ---> Using cache
 ---> 28067d6e7d87
Step 8/9 : COPY . .
 ---> 243b74936872
Step 9/9 : CMD [ "npm", "start" ]
 ---> Running in 888d96b0f679
Removing intermediate container 888d96b0f679
 ---> 8f3d06e9c358
Successfully built 8f3d06e9c358
Successfully tagged slack-twitter-bot_server:latest
+ docker-compose down --remove-orphans
Removing network slack-twitter-bot_default
+ docker-compose up -d --remove-orphans
Creating network "slack-twitter-bot_default" with the default driver
Creating slack-twitter-bot_server_1 ... done
root@vm-standard-a1-flex:~/slack-twitter-bot#

**Comment by szsyzx** [comment]
![image](https://user-images.githubusercontent.com/21995452/182202842-f5b4d3ee-34c9-4461-aad6-d4dab36bf0d9.png)

Why is there no message from my slcak anything? How do I need to use it?

**Comment by sapphire-sh** [comment]
you should remove `{{` and `}}` from urls.

**Comment by szsyzx** [comment]
![image](https://user-images.githubusercontent.com/21995452/182203581-19cd0d8e-eeaf-411f-89a3-31d4131b262c.png)
Now it's right, I built it well! Why no news from slack channel?

**Comment by sapphire-sh** [comment]
I can think of several causes,
1. incorrect filename ? 
2. invalid list id
3. invalid twitter token ?

or you can retrieve docker logs by executing `docker logs -f slack-twitter-bot_server_1`
this may show the cause of the problem.

and the server invokes twitter crawling every 5 minutes, so you may wait a while to get your messages.

![182203581-19cd0d8e-eeaf-411f-89a3-31d4131b262c](https://user-images.githubusercontent.com/3864286/182204608-c74c7b6b-3ec0-415f-9f18-337daa03bfbe.png)

file structure should look like below.

<img width="764" alt="Screen Shot 2022-08-02 at 2 06 54" src="https://user-images.githubusercontent.com/3864286/182205201-5cc03f2a-7847-42f9-9ed8-0a22a70abf0a.png">

**Comment by sapphire-sh** [comment]
may I see your docker logs?
it should print logs like below

<img width="682" alt="Screen Shot 2022-08-02 at 2 20 46" src="https://user-images.githubusercontent.com/3864286/182206682-24dc0be3-afff-4d82-849f-548154b5af36.png">

**Comment by szsyzx** [comment]
![image](https://user-images.githubusercontent.com/21995452/182208132-ee6c0346-1e5d-45d3-ae5d-8a0c8a78022c.png)

**Comment by sapphire-sh** [comment]
oh… I forgot to specify `sqlite3` package in the `package.json`.
I have made a fix commit, so please retry after pull or re-clone.

https://github.com/sapphire-sh/slack-twitter-bot/commit/6e7befc964467f8076195df2de6501d4e2a24f7f

**Comment by szsyzx** [comment]
@sapphire-sh 
![image](https://user-images.githubusercontent.com/21995452/182209908-559ed9cb-517e-4ac6-8679-856481507090.png)
Is it running properly? Is it possible to add keyword monitoring? And is it possible to customize the push time?

**Comment by szsyzx** [comment]
![image](https://user-images.githubusercontent.com/21995452/182211261-830be501-9763-4729-b705-8c6a96959838.png)
There's a problem
@sapphire-sh Is there something wrong with my settings?

**Comment by sapphire-sh** [comment]
you may fix here to change twitter crawling interval.
https://github.com/sapphire-sh/slack-twitter-bot/blob/6e7befc964467f8076195df2de6501d4e2a24f7f/src/index.ts#L9
  - you may encounter twitter api rate limit if crawling interval is too short.
  - please refer https://en.wikipedia.org/wiki/Cron#Overview for cronjob syntax.

currently, it does not support search api.

**Comment by szsyzx** [comment]
![image](https://user-images.githubusercontent.com/21995452/182212412-c47a15f7-ea66-4f45-9a22-ef0f68102323.png)
Is this the right setting?

**Comment by sapphire-sh** [comment]
> ![image](https://user-images.githubusercontent.com/21995452/182212412-c47a15f7-ea66-4f45-9a22-ef0f68102323.png) Is this the right setting?

since you have retrieved your tweet properly here, I think your twitter token is all right.
https://github.com/sapphire-sh/slack-twitter-bot/issues/1#issuecomment-1201524186

**Comment by sapphire-sh** [comment]
> ![image](https://user-images.githubusercontent.com/21995452/182211261-830be501-9763-4729-b705-8c6a96959838.png) There's a problem @sapphire-sh Is there something wrong with my settings?

I have made a fix commit, so please retry after pull.
I have tested in my local environment, so it should run fine this time.
sorry for making you confusing :(

https://github.com/sapphire-sh/slack-twitter-bot/commit/4e056ae9ed4b60e2964abcca6b0c5762b9811ceb

**Comment by szsyzx** [comment]
Do you have a live chat tool, such as Telegram, to facilitate the exchange of questions?

**Comment by sapphire-sh** [comment]
@szsyzx can you try gitter? https://gitter.im/sapphire-sh/slack-twitter-bot

**Comment by sapphire-sh** [comment]
👍
