### ISSUE TITLE
Is it possible to exclude hashtags

### ISSUE THREAD

**Issue by szsyzx** [sapphire-sh/slack-twitter-bot#3]
For example, my search keyword is "Suzhou", but the search results show a lot of tweets containing "#Suzhou".

**Comment by sapphire-sh** [comment]
use `filter_keywords` attribute
e.g.) this will send for tweets with "text" but exclude tweets with "#test"
```json
  {
    "type": "search",
    "value": "test",
    "attributes": [
      ["filter_keywords", "#test"]
    ]
  }
```
