### ISSUE TITLE
The project so far can be said to be perfect, I wonder if this feature can be added

### ISSUE THREAD

**Issue by szsyzx** [sapphire-sh/slack-twitter-bot#4]
![image](https://user-images.githubusercontent.com/21995452/184069983-bec2492b-0c52-4f8a-b6f2-53786747306b.png)
The project so far can be said to be perfect, I wonder if this feature can be added

**Comment by sapphire-sh** [comment]
please check https://github.com/sapphire-sh/slack-twitter-bot/commit/014ee106eeb262262c335bd1caf41de91ccec471
